# Generated by Django 3.1.1 on 2025-03-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20250319_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlisting',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
