# Generated by Django 3.1.1 on 2025-03-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_roomimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomlisting',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RemoveField(
            model_name='roomlisting',
            name='mobile_number',
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='listings.roomlisting'),
        ),
    ]
