# Generated by Django 3.1.1 on 2025-03-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20250319_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cooler', 'Cooler'), ('Fridge', 'Fridge'), ('Washing Machine', 'Washing Machine'), ('Fully Furnished', 'Fully Furnished'), ('Air Conditioning', 'Air Conditioning'), ('WiFi', 'WiFi'), ('Parking', 'Parking'), ('Hot Water', 'Hot Water')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='for_whom',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('All', 'All')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='room_type',
            field=models.CharField(blank=True, choices=[('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('PG', 'PG'), ('Hostel', 'Hostel'), ('Guest House', 'Guest House'), ('Flat', 'Flat')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='listings.Facility'),
        ),
    ]
