# Generated by Django 3.1.1 on 2025-03-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20250320_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomlisting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
