# Generated by Django 3.1.1 on 2025-03-20 15:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0011_roomlisting_contact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='roomlisting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +911234567890).', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Enter your contact number (e.g., +911234567890) for users to reach you.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +911234567890).', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='listings.Facility'),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='for_whom',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('all', 'All')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='main_image',
            field=models.ImageField(blank=True, default='room_pics/default_room.jpg', null=True, upload_to='room_pics/'),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='room_type',
            field=models.CharField(blank=True, choices=[('single_room', 'Single Room'), ('double_room', 'Double Room'), ('pg', 'PG'), ('hostel', 'Hostel'), ('guest_house', 'Guest House'), ('flat', 'Flat')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
